[package]
name = "ssh-unlock"
version = "1.0.2"
authors = ["115100 <115100@users.noreply.github.com>"]
edition = "2018"

[dependencies]
libc = "0.2.61"
nix = "0.15.0"

[profile.release]
lto = true
panic = 'abort'
